# Form implementation generated from reading ui file 'registration_window.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_registration_window(object):
    def setupUi(self, registration_window):
        registration_window.setObjectName("registration_window")
        registration_window.resize(400, 350)
        registration_window.setMinimumSize(QtCore.QSize(400, 350))
        registration_window.setMaximumSize(QtCore.QSize(400, 300))
        self.centralwidget = QtWidgets.QWidget(parent=registration_window)
        self.centralwidget.setObjectName("centralwidget")
        self.name_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.name_label.setGeometry(QtCore.QRect(10, 30, 71, 16))
        self.name_label.setObjectName("name_label")
        self.username_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.username_label.setGeometry(QtCore.QRect(10, 70, 71, 16))
        self.username_label.setObjectName("username_label")
        self.password_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.password_label.setGeometry(QtCore.QRect(10, 110, 71, 16))
        self.password_label.setObjectName("password_label")
        self.validation_txt = QtWidgets.QLabel(parent=self.centralwidget)
        self.validation_txt.setGeometry(QtCore.QRect(100, 300, 171, 16))
        self.validation_txt.setObjectName("validation_txt")
        self.user_name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.user_name.setGeometry(QtCore.QRect(85, 30, 120, 21))
        self.user_name.setObjectName("user_name")
        self.user_username = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.user_username.setGeometry(QtCore.QRect(85, 68, 120, 21))
        self.user_username.setObjectName("user_username")
        self.user_password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.user_password.setGeometry(QtCore.QRect(85, 107, 120, 21))
        self.user_password.setObjectName("user_password")
        self.checking_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.checking_label.setGeometry(QtCore.QRect(10, 170, 121, 16))
        self.checking_label.setObjectName("checking_label")
        self.user_checking_balance = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.user_checking_balance.setGeometry(QtCore.QRect(140, 170, 120, 21))
        self.user_checking_balance.setObjectName("user_checking_balance")
        self.checking_label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.checking_label_2.setGeometry(QtCore.QRect(10, 200, 121, 16))
        self.checking_label_2.setObjectName("checking_label_2")
        self.optional_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.optional_text.setGeometry(QtCore.QRect(120, 140, 111, 16))
        self.optional_text.setObjectName("optional_text")
        self.user_savings_balance = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.user_savings_balance.setGeometry(QtCore.QRect(140, 200, 120, 21))
        self.user_savings_balance.setObjectName("user_savings_balance")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80, 240, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.return_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.return_button.setGeometry(QtCore.QRect(210, 240, 113, 32))
        self.return_button.setObjectName("return_button")
        registration_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=registration_window)
        self.statusbar.setObjectName("statusbar")
        registration_window.setStatusBar(self.statusbar)

        self.retranslateUi(registration_window)
        QtCore.QMetaObject.connectSlotsByName(registration_window)

    def retranslateUi(self, registration_window):
        _translate = QtCore.QCoreApplication.translate
        registration_window.setWindowTitle(_translate("registration_window", "Registration"))
        self.name_label.setText(_translate("registration_window", "Name"))
        self.username_label.setText(_translate("registration_window", "Username"))
        self.password_label.setText(_translate("registration_window", "Password"))
        self.validation_txt.setText(_translate("registration_window", "feedback"))
        self.checking_label.setText(_translate("registration_window", "Checking balance"))
        self.checking_label_2.setText(_translate("registration_window", "Savings balance "))
        self.optional_text.setText(_translate("registration_window", "(Optional)"))
        self.pushButton.setText(_translate("registration_window", "Register"))
        self.return_button.setText(_translate("registration_window", "Return"))
