# Form implementation generated from reading ui file 'proj1_mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_login_window(object):
    def setupUi(self, login_window):
        login_window.setObjectName("login_window")
        login_window.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        login_window.resize(450, 250)
        login_window.setMinimumSize(QtCore.QSize(450, 250))
        login_window.setMaximumSize(QtCore.QSize(450, 250))
        self.centralwidget = QtWidgets.QWidget(parent=login_window)
        self.centralwidget.setObjectName("centralwidget")
        self.Account_num_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Account_num_label.setEnabled(False)
        self.Account_num_label.setGeometry(QtCore.QRect(10, 20, 70, 50))
        self.Account_num_label.setMinimumSize(QtCore.QSize(50, 50))
        self.Account_num_label.setBaseSize(QtCore.QSize(0, 0))
        self.Account_num_label.setAutoFillBackground(True)
        self.Account_num_label.setObjectName("Account_num_label")
        self.Account_num_label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Account_num_label_2.setEnabled(False)
        self.Account_num_label_2.setGeometry(QtCore.QRect(10, 70, 70, 50))
        self.Account_num_label_2.setMinimumSize(QtCore.QSize(50, 50))
        self.Account_num_label_2.setBaseSize(QtCore.QSize(0, 0))
        self.Account_num_label_2.setAutoFillBackground(True)
        self.Account_num_label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Account_num_label_2.setObjectName("Account_num_label_2")
        self.signin_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.signin_button.setGeometry(QtCore.QRect(110, 140, 113, 32))
        self.signin_button.setAutoFillBackground(True)
        self.signin_button.setObjectName("signin_button")
        self.feedback_txt = QtWidgets.QLabel(parent=self.centralwidget)
        self.feedback_txt.setGeometry(QtCore.QRect(49, 190, 251, 20))
        self.feedback_txt.setText("")
        self.feedback_txt.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.feedback_txt.setObjectName("feedback_txt")
        self.username_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.username_input.setGeometry(QtCore.QRect(100, 32, 150, 21))
        self.username_input.setObjectName("username_input")
        self.password_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.password_input.setGeometry(QtCore.QRect(100, 81, 150, 21))
        self.password_input.setInputMask("")
        self.password_input.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_input.setObjectName("password_input")
        login_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=login_window)
        self.statusbar.setObjectName("statusbar")
        login_window.setStatusBar(self.statusbar)

        self.retranslateUi(login_window)
        QtCore.QMetaObject.connectSlotsByName(login_window)

    def retranslateUi(self, login_window):
        _translate = QtCore.QCoreApplication.translate
        login_window.setWindowTitle(_translate("login_window", "Log in"))
        self.Account_num_label.setText(_translate("login_window", "Username"))
        self.Account_num_label_2.setText(_translate("login_window", "Password"))
        self.signin_button.setText(_translate("login_window", "Sign in"))
